### ISSUE TITLE
Arquivo .env

### ISSUE THREAD

**Issue by geich** [wsfloriano/product-api#1]
@wsfloriano o backend necessita de um arquivo .env
"_Configuração via .env: Configurações de ambiente utilizando variáveis no arquivo .env._"

Porém não achei nenhuma referência esse arquivo na descrição, quais variáveis precisa ter nesse arquivo? Preciso rodar alguma infra local para conseguir rodar?

**Comment by wsfloriano** [comment]
@geich Adicionado env.example.
Atualizei também a informação sobre o DB no Readme, informando a necessidade de criação conforme o exemplo contido no assessment.
